services:
  postgres:
    container_name: postgree_container
    image: postgres:latest  # Corrected the image name
    environment:
      POSTGRES_USER: username  # Corrected environment variable names
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: bookSocialNetworks
    volumes:
      - postgres:/var/lib/postgresql/data  # Use the named volume here
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped 

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
